### ISSUE TITLE
Jounrey --> Journey

### ISSUE THREAD

**Issue by yoongi0428** [hojinYang/hojinYang.github.io#1]
Hi.
I found a typo while I was reading your blog.

In config.yaml, there you wrote "Life is a jounrey", which you meant "journey"!
BTW, I find your blog very interesting, so keep it up!

**Comment by yoongi0428** [comment]
Oh, it was "Jounrey is a reward"

**Comment by hojinYang** [comment]
Thanks for your kind words! :)
